name: Test

permissions:
  contents: read
  actions: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POETRY_VERSION: 1.4.0
  BUILD_PYTHON_VERSION: 3.12

jobs:

  # Testing Job
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry==${{ env.POETRY_VERSION }}

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry

    - name: Install dependencies
      run: |
        poetry install --without experiments --without docs

    - name: Run tests with coverage
      continue-on-error: true
      run: |
          poetry run pytest --cov=fpboost --cov-report=xml --cov-report=html --junitxml=reports/test-results.xml

    - name: Upload coverage report
      if: ${{ matrix.python-version == '3.12' }}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: reports/

  # Build job
  build_package:
    name: Build package
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}
          cache: poetry

      - name: Build package
        run: poetry build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
