name: Build

permissions:
  contents: read

env:
  POETRY_VERSION: 1.4.0
  PYTHON_VERSON: 3.12

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSON }}
          cache: poetry

      - name: Build package
        run: poetry build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
